version: '3.4'

services: 
  classfiles:
    container_name: classfiles
    image: classfiles
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   DB_HOST: host.docker.internal
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
    # extra_hosts:
    # - "host.docker.internal:host-gateway"

  # using service name as mysql and the same name is used as the db host in the env file,
  # because the service name is a valid hostname which can be used inside other conatiners to access that service
  mysql:
    container_name: mysql-docker
    image: mysql:5.7-debian
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u root -p$$MYSQL_ROOT_PASSWORD ping -h localhost"]
      timeout: 5s
      retries: 10