version: '3.4'

services:
  classfiles:
    container_name: classfiles
    image: classfiles
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - ./.docker.env
    ports:
      - 3000:3000
    extra_hosts:
    - "host.docker.internal:host-gateway"