version: '3.4'

services: 
  classfiles:
    container_name: classfiles
    # image: chaitanyadocker1/class-files:production
    image: class-files
    build:
      context: .
      dockerfile: ./Dockerfile
      target: local
    # environment:
      # DB_HOST: host.docker.internal
    environment:
      # - NODE_ENV=production
      - NODE_ENV=development
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
    # extra_hosts:
    # - "host.docker.internal:host-gateway"

  # using service name as mysql and the same name is used as the db host in the env file,
  # because the service name is a valid hostname which can be used inside other conatiners to access that service
  mysql:
    container_name: mysql-docker
    image: mysql:5.7-debian
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 33060:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u root -p$$MYSQL_ROOT_PASSWORD ping -h localhost"]
      timeout: 5s
      retries: 10