version: '3.4'

services:
  classfiles:
    container_name: classfiles
    image: classfiles
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: host.docker.internal
    env_file:
      - ./.env
    ports:
      - 3000:3000
    extra_hosts:
    - "host.docker.internal:host-gateway"